// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublikoAPI.Data;

namespace PublikoAPI.Migrations
{
    [DbContext(typeof(PublikoPagesDBContext))]
    [Migration("20210921132813_Genesis")]
    partial class Genesis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PublikoSharedLibrary.Models.WebPage", b =>
                {
                    b.Property<string>("PageID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PageDateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PageDateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PageID");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("PublikoSharedLibrary.Models.WebPost", b =>
                {
                    b.Property<string>("PostID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostDateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostDateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostID");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
